### ISSUE TITLE
Default buffer size allocates in LOH and brings a lot of GC overhead.

### ISSUE THREAD

**Issue by azhmur** [bp74/Zstandard.Net#2]
Buffer sizes are taken from zstd native. Right now they are nearly 132 KB. This is beyong LOH boundary.
Replacing this buffer size with GC 0 gen friendly value 80 KB removes a lot of GC collections in my tests.

It is quite easy to add buffer size parameter to constructor, but i also suppose replacing default values as well.

PS My tests contains some licensed code so i can't publish it, but these results can be easily reproduced. 

Decompress with native buffer size.
```
|   Method |         Mean |        Error |     StdDev | Scaled | ScaledSD |   Gen 0 |   Gen 1 |   Gen 2 | Allocated |
|--------- |-------------:|-------------:|-----------:|-------:|---------:|--------:|--------:|--------:|----------:|
|      Raw |     7.610 us |     6.268 us |  0.3542 us |   1.00 |     0.00 |  1.1597 |  0.0763 |       - |  94.14 KB |
| SevenZip | 4,277.657 us | 1,512.490 us | 85.4585 us | 562.88 |    22.77 |       - |       - |       - |  35.58 KB |
|      Lz4 |    14.420 us |    10.388 us |  0.5870 us |   1.90 |     0.09 |  1.2817 |  0.1373 |       - | 113.39 KB |
|  Deflate |    96.853 us |     7.785 us |  0.4398 us |  12.74 |     0.47 |  1.8311 |  0.1221 |       - |  143.9 KB |
|     Zstd |   113.749 us |    32.414 us |  1.8314 us |  14.97 |     0.59 | 37.1094 | 37.1094 | 37.1094 | 222.71 KB |
```

Decompress with buffer size 80 KB.
```
|   Method |         Mean |      Error |     StdDev | Scaled | ScaledSD |  Gen 0 |  Gen 1 | Allocated |
|--------- |-------------:|-----------:|-----------:|-------:|---------:|-------:|-------:|----------:|
|      Raw |     7.674 us |   2.895 us |  0.1636 us |   1.00 |     0.00 | 1.1597 | 0.0916 |  94.14 KB |
| SevenZip | 4,222.292 us | 497.412 us | 28.1047 us | 550.38 |    10.06 |      - |      - |  35.46 KB |
|      Lz4 |    16.250 us |  13.703 us |  0.7742 us |   2.12 |     0.09 | 1.2817 | 0.1221 | 113.38 KB |
|  Deflate |    98.037 us |  11.914 us |  0.6731 us |  12.78 |     0.23 | 1.7090 | 0.1221 |  143.9 KB |
|     Zstd |    62.336 us |   8.185 us |  0.4625 us |   8.13 |     0.15 | 1.9531 |      - |  172.7 KB |

**Comment by bp74** [comment]
Thanks for the analysis, this looks very interessting. I will do some tests myself and adjust the buffer size according to your numbers.

**Comment by bp74** [comment]
Finally i had some time to take a look at this. Even if you reduce the size of the buffer you still get a lot of memory allocations. When you compress lots of streams you create a lot of garbage which will trigger a gen1 collection. So i thought about an internal pool of buffers which i implemented here: b52a28027dd378f86b616153150cd7963f89338e

What do you think about this solution?

**Comment by bp74** [comment]
I've changed the implementation again by using the shared ArrayPool<byte> from the System.Buffers class.  This one is also used in Stream.CopyTo and other classes in the BCL.

**Comment by azhmur** [comment]
That is great! Thanks a lot!

**Comment by bp74** [comment]
I will upload it to NuGet tomorrow.
